### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by bvasiles** [brettlangdon/jsnice#4]
I'm running `jsnice --no-types` with the code in the example from http://jsnice.org as input:

```
function chunkData(e, t) {
  var n = [];
  var r = e.length;
  var i = 0;
  for (; i < r; i += t) {
    if (i + t < r) {
      n.push(e.substring(i, i + t));
    } else {
      n.push(e.substring(i, r));
    }
  }
  return n;
}
```

It returns:

```
function chunkData(local$$2, local$$3) {
  var local$$6 = [];
  var local$$10 = local$$2.length;
  var local$$13 = 0;
  for (;local$$13 < local$$10;local$$13 += local$$3) {
    if (local$$13 + local$$3 < local$$10) {
      local$$6.push(local$$2.substring(local$$13, local$$13 + local$$3));
    } else {
      local$$6.push(local$$2.substring(local$$13, local$$10));
    }
  }
  return local$$6;
}
;
```

**Comment by brettlangdon** [comment]
@bvasiles please update to `v0.2.0`, this is resolved.

The problem was that jsnice.org takes an option `suggest` which will create generic local variables like in your example. This option was enabled by default in this library. I have updated the code to make it be disabled by default and now expose a command line option to enable it.
